module.exports = [
  {
    id: 1,
    name: 'Camera',
    image: require('./image-1.json'),
    createdAt: new Date(2023, 5, 1),
    updatedAt: new Date(2023, 5, 1),
  },
  {
    id: 2,
    name: 'Desktop',
    image: require('./image-2.json'),
    createdAt: new Date(2023, 5, 1),
    updatedAt: new Date(2023, 5, 1),
  },
  {
    id: 3,
    name: 'Drone',
    image: require('./image-3.json'),
    createdAt: new Date(2023, 5, 2),
    updatedAt: new Date(2023, 5, 2),
  },
  {
    id: 4,
    name: 'Entertainment',
    image: require('./image-4.json'),
    createdAt: new Date(2023, 5, 2),
    updatedAt: new Date(2023, 5, 2),
  },
  {
    id: 5,
    name: 'Laptop',
    image: require('./image-5.json'),
    createdAt: new Date(2023, 5, 3),
    updatedAt: new Date(2023, 5, 3),
  },
  {
    id: 6,
    name: 'Audio',
    image: require('./image-6.json'),
    createdAt: new Date(2023, 5, 3),
    updatedAt: new Date(2023, 5, 3),
  },
  {
    id: 7,
    name: 'Smartband',
    image: require('./image-7.json'),
    createdAt: new Date(2023, 5, 4),
    updatedAt: new Date(2023, 5, 4),
  },
  {
    id: 8,
    name: 'Smartphone',
    image: require('./image-8.json'),
    createdAt: new Date(2023, 5, 4),
    updatedAt: new Date(2023, 5, 4),
  },
  {
    id: 9,
    name: 'Smartwatch',
    image: require('./image-9.json'),
    createdAt: new Date(2023, 5, 5),
    updatedAt: new Date(2023, 5, 5),
  },
  {
    id: 10,
    name: 'Tablet',
    image: require('./image-10.json'),
    createdAt: new Date(2023, 5, 5),
    updatedAt: new Date(2023, 5, 5),
  },
];
